"use client"
import { useState } from "react"

const GIFS = [
  { id: "YtXhHnouybHEmT7Xkh", title: "So Good", cat: "happy" },
  { id: "roSEVPxDsbKiQB5N6V", title: "Happy Party", cat: "happy" },
  { id: "wlNT7dI3zZjVV3m2Au", title: "Happy Dance", cat: "happy" },
  { id: "l1J9Pbg4jOpgKaW9q", title: "Happy Party 2", cat: "happy" },
  { id: "YXsXWYNmn8A9xMCmMD", title: "Excited Dance", cat: "happy" },
  { id: "BjNMiLuMsLL2gu4gtl", title: "Happy Hip Hop", cat: "happy" },
  { id: "NCF5DMDvf9247pmp72", title: "Dance Party", cat: "happy" },
  { id: "M9jZ8PFwQzBXXJryBL", title: "Good Vibes", cat: "happy" },
  { id: "4aY8hI9hHAJD0ofEpo", title: "Dance Party 2", cat: "happy" },
  { id: "kPMBkmGYByXmJsGVL3", title: "Happy Dance 2", cat: "happy" },
  { id: "3bA4HdmfwyDpiWIas9", title: "Dance Party 3", cat: "happy" },
  { id: "3oEjI6SIIHBdRxXI40", title: "Dance Party", cat: "happy" },
  { id: "5GoVLqeAOo6PK", title: "Celebrate", cat: "happy" },
  { id: "AGOPaltgJ2pBC", title: "Thumbs Up", cat: "happy" },
  { id: "3o7aD5oU9qcCuAe9SU", title: "Happy", cat: "happy" },
  { id: "26FmRCAX6ryFKar0A", title: "Awesome", cat: "happy" },
  { id: "Kwi0Iu9MxxOgg", title: "Smile", cat: "happy" },
  { id: "X0Puqlx2pTy4E", title: "Reaction", cat: "happy" },
  { id: "3o7btYetccbRYL4WVW", title: "Sweet", cat: "happy" },
  { id: "EdFu9m8ckGO3e", title: "Happy Love", cat: "happy" },
  { id: "26FxFNB4oAgwcwBry", title: "Audience Reaction", cat: "lol" },
  { id: "l2QEeYqA9urBERX8I", title: "No Thanks", cat: "lol" },
  { id: "Z6DPKw6gyCYz4zEsxk", title: "Mic Drop", cat: "lol" },
  { id: "hyyV7pnbE0FqLNBAzs", title: "No", cat: "lol" },
  { id: "whQCarjn5Jv1Ktq2HH", title: "Facepalm", cat: "lol" },
  { id: "TzdTYRpcoHdrdoo15p", title: "Oh No", cat: "lol" },
  { id: "RsIm2nJA5AVjMWfEaL", title: "Office No", cat: "lol" },
  { id: "26BRuo6sLetdllPAQ", title: "Hilarious", cat: "lol" },
  { id: "26ufdipQqU2lhNA4g", title: "Funny", cat: "lol" },
  { id: "F3BeiZNq6VbDwyxzxF", title: "The Office", cat: "lol" },
  { id: "xT1XGU1AHz9Fe8tmp2", title: "Schitt's Creek", cat: "lol" },
  { id: "FcuiZUneg1YRAu1lH2", title: "Always Sunny", cat: "lol" },
  { id: "hXD3cypLkycW1hQTFz", title: "SNL", cat: "lol" },
  { id: "KBfKueAjIJV8Q", title: "Finger Guns", cat: "lol" },
  { id: "3o9bJX4O9ShW1L32eY", title: "Shameless", cat: "lol" },
  { id: "eB1muFfUvQrZkoJa16", title: "Schitt's Creek", cat: "lol" },
  { id: "xUOwGhdl13FVkoWpb2", title: "Give Me A Break", cat: "lol" },
  { id: "fJliUiYbvEIoM", title: "Do You Even Lift", cat: "lol" },
  { id: "P18aB31TcT7DBpkyUh", title: "Keep Talking", cat: "lol" },
  { id: "oxCtqUm9PhXvA0oXnp", title: "Forever LOL", cat: "lol" },
  { id: "0NwSQpGY6ipgOSt8LL", title: "Mind Blown", cat: "wow" },
  { id: "PadfCrnNVQzozq6A0m", title: "John Cena", cat: "wow" },
  { id: "6kz2FMFCMNeNpULQ3p", title: "Wow", cat: "wow" },
  { id: "2hEEHLafH4KFQ6pUEA", title: "React Wow", cat: "wow" },
  { id: "XrWwIchnRfynuvlpRF", title: "Wait What", cat: "wow" },
  { id: "xTiTnBMEz7zAKs57LG", title: "Awesome", cat: "wow" },
  { id: "XJtM2nNFCzT3etvzOB", title: "Shocked", cat: "wow" },
  { id: "Rlwz4m0aHgXH13jyrE", title: "No Way", cat: "wow" },
  { id: "R8s2pWPslY0dG", title: "Mind Blown", cat: "wow" },
  { id: "100QWMdxQJzQC4", title: "Whoa", cat: "wow" },
  { id: "QWw4hc5gTnJhY0BUI3", title: "Whoa", cat: "wow" },
  { id: "rWgLOxrdNNDzUXaQnd", title: "Blink Confused", cat: "wow" },
  { id: "3o7TKJLO3D4kUgpa6I", title: "Shocked", cat: "wow" },
  { id: "bdVGuPnfR3g9PrZU9d", title: "Sad Cry", cat: "sad" },
  { id: "rVudQoqKFHuJ0Xmnym", title: "Sad Bye", cat: "sad" },
  { id: "Rf5Kq1IXnxilMczBI5", title: "Sad Mood", cat: "sad" },
  { id: "qyo2cylDCIiCmuw0Ce", title: "Disappointed", cat: "sad" },
  { id: "wG7JgE083zaHqXzUyq", title: "Crying Tired", cat: "sad" },
  { id: "z7ru2U63UquVwPTu7W", title: "Sad Cry 2", cat: "sad" },
  { id: "t6JFpRFhBTkVib7ju1", title: "Sad", cat: "sad" },
  { id: "1qB3EwE3c54A", title: "Depressed", cat: "sad" },
  { id: "I6NHpPGnq4ed2", title: "Cute", cat: "cute" },
  { id: "d1E2IByItLUuONMc", title: "Aww", cat: "cute" },
  { id: "6pUBXVTai18Iw", title: "So Cute", cat: "cute" },
  { id: "Xev2JdopBxGj1LuGvt", title: "Adorable", cat: "cute" },
  { id: "lcySndwSDLxC4eOU86", title: "Sweet", cat: "cute" },
  { id: "Nm8ZPAGOwZUQM", title: "Kitten", cat: "cute" },
  { id: "cwTtbmUwzPqx2", title: "Puppy", cat: "cute" },
  { id: "SEp6Zq6ZkzUNW", title: "Aww Thanks", cat: "cute" },
  { id: "65ATXZgKw9tKnJua1B", title: "Baby", cat: "cute" },
  { id: "dT7LBdAZP1Rh6", title: "Angry", cat: "angry" },
  { id: "SB5fjrUhAeLte", title: "Mad", cat: "angry" },
  { id: "gl8ymnpv4Sqha", title: "Furious", cat: "angry" },
  { id: "yS2AMt4LX13Mc", title: "Annoyed", cat: "angry" },
  { id: "JfDNFU1qOZna", title: "Seriously?", cat: "angry" },
  { id: "3o6EhU7SUa3afFIJFe", title: "Not Happy", cat: "angry" },
  { id: "SJX3gbZ2dbaEhU92Pu", title: "Unbelievable", cat: "angry" },
  { id: "SDogLD4FOZMM8", title: "Kidding Me", cat: "angry" },
  { id: "XzsQ4z8EhOPBOfpSMK", title: "Shut Up", cat: "angry" },
  { id: "BbBPp0eMeykg46LLk6", title: "Seriously", cat: "angry" },
  { id: "5t9wJjyHAOxvnxcPNk", title: "Frustrated", cat: "angry" },
  { id: "XMcgqIA49OywU", title: "Love", cat: "love" },
  { id: "JmBXdjfIblJDi", title: "I Love It", cat: "love" },
  { id: "kMdlyJ74u9khW", title: "Heart", cat: "love" },
  { id: "cFOaorIxCo8Ra", title: "In Love", cat: "love" },
  { id: "l0MYEqEzwMWFCg8rm", title: "Heart Eyes", cat: "love" },
  { id: "AANqYGD9LVsw8", title: "Love You", cat: "love" },
  { id: "11qAyKz9AbFEYM", title: "Be Mine", cat: "love" },
  { id: "3o6ZtmGkSCwGWQNTOg", title: "I Love You", cat: "love" },
  { id: "3o7TKLSqjNPNs19nDG", title: "Forever", cat: "love" },
  { id: "bEcDN4ifb3POkX7Vs4", title: "XOXO", cat: "love" },
  { id: "xTiN0CNHgoRf1Ha7CM", title: "Jersey Love", cat: "love" },
  { id: "2pU8T0OTNkmre", title: "Love It", cat: "love" },
  { id: "��cPZdap8PGhSvABr6xW", title: "Happy 1", cat: "happy" },
  { id: "ar9f7kG6erzQk", title: "Happy 2", cat: "happy" },
  { id: "t22XfyAwh0Qla", title: "Lol 1", cat: "lol" },
  { id: "Zn7rsVqBTPAly", title: "Happy 3", cat: "happy" },
  { id: "26tn84fF0eL3c898c", title: "Wow 1", cat: "wow" },
  { id: "PnTbJDFX0q9IDKnqyx", title: "Lol 2", cat: "lol" },
  { id: "pt0EKLDJmVvlS", title: "Wow 2", cat: "wow" },
  { id: "79mW5NqDZUb62Rcr6U", title: "Wow 3", cat: "wow" },
  { id: "efqoQtkftSYOQ", title: "Wow 4", cat: "wow" },
  { id: "SoWrwCZB7kVYA", title: "Angry 1", cat: "angry" },
  { id: "4dL4eV4pNb3MY", title: "Happy 4", cat: "happy" },
  { id: "11shDO8NnZDYpa", title: "Angry 2", cat: "angry" },
  { id: "4JB134lkbtzoUhRDZg", title: "Happy 5", cat: "happy" },
  { id: "iO4ptP2iuV29yui3mx", title: "Lol 3", cat: "lol" },
  { id: "eFk4QXIkq5NOwHbMEa", title: "Wow 5", cat: "wow" },
  { id: "QYMJR51O9sSZO", title: "Lol 4", cat: "lol" },
  { id: "fSSbirL3Ew0zC", title: "Lol 5", cat: "lol" },
  { id: "dbUmJJ2bqZjSDQpsYx", title: "Sad 1", cat: "sad" },
  { id: "gZQ7NsdTXM86ZLPpdN", title: "Happy 6", cat: "happy" },
  { id: "3o85xJWqnjH1Xu5rmE", title: "Wow 6", cat: "wow" },
  { id: "Af7ap9r7NzJJe", title: "Lol 6", cat: "lol" },
  { id: "x0qP0643fys3wnt4uP", title: "Sad 2", cat: "sad" },
  { id: "sRKg9r2YWeCTG5JTTo", title: "Happy 7", cat: "happy" },
  { id: "xUOxeUqZbV4vSPBXt6", title: "Cute 1", cat: "cute" },
  { id: "Zpmu1zdU8kA8n92LBT", title: "Wow 7", cat: "wow" },
  { id: "nXUCkgH6BmigU", title: "Lol 7", cat: "lol" },
  { id: "KFhv3T1seYSJuak8TN", title: "Happy 8", cat: "happy" },
  { id: "l0IydB4EKFpSPa6NG", title: "Cute 2", cat: "cute" },
  { id: "l41Yzhskh3BycmxEY", title: "Happy 9", cat: "happy" },
  { id: "xoRaAV8X227rG", title: "Happy 10", cat: "happy" },
  { id: "NZesNrMPP8jtMGmUTQ", title: "Love 1", cat: "love" },
  { id: "uADTQTTlpQWeydiHfs", title: "Wow 8", cat: "wow" },
  { id: "mYZnB29KHRrxe", title: "Wow 9", cat: "wow" },
  { id: "3ogxB6sfYFL3IYlBU4", title: "Sad 3", cat: "sad" },
  { id: "1SymAX7raq13OvyzLg", title: "Happy 11", cat: "happy" },
  { id: "fLv2F5rMY2YWk", title: "Love 2", cat: "love" },
  { id: "ul3DvfCRQixLa", title: "Wow 10", cat: "wow" },
  { id: "ac7MA7r5IMYda", title: "Lol 8", cat: "lol" },
  { id: "fnK0jeA8vIh2QLq3IZ", title: "Lol 9", cat: "lol" },
  { id: "aEK2Ln4nChX4UWFXal", title: "Lol 10", cat: "lol" },
  { id: "EizX1bK3LlD20", title: "Happy 12", cat: "happy" },
  { id: "cirKPyIvk9Wo6uoqnX", title: "Wow 11", cat: "wow" },
  { id: "3ofT5VgD5NOgKbYlna", title: "Love 3", cat: "love" },
  { id: "lH6KM3wmpG1ck", title: "Happy 13", cat: "happy" },
  { id: "FWtVYDHIxgGgE", title: "Wow 12", cat: "wow" },
  { id: "2Zx1Pa8Fcs9xu", title: "Wow 13", cat: "wow" },
  { id: "wWjN6nhOvMgAo", title: "Wow 14", cat: "wow" },
  { id: "oxU4aYICwH4Aymx1jt", title: "Lol 11", cat: "lol" },
  { id: "xTk9ZzD6NuYrMuDBx6", title: "Lol 12", cat: "lol" },
  { id: "S67m7E7yH5Wta", title: "Wow 15", cat: "wow" },
  { id: "6hFYEKVFG885dCAnbZ", title: "Lol 13", cat: "lol" },
  { id: "ra75UYT9LjKSY", title: "Angry 3", cat: "angry" },
  { id: "3o6Ztaj8KHCx07iFpK", title: "Cute 3", cat: "cute" },
  { id: "3o6ZsY3ewBxdgA1S92", title: "Cute 4", cat: "cute" },
  { id: "DoCIC5Pxp57qg", title: "Sad 4", cat: "sad" },
  { id: "wFk7roIpDeXC0", title: "Love 4", cat: "love" },
  { id: "VGthqYKqyKhipYxK2s", title: "Happy 14", cat: "happy" },
  { id: "byTVPe9Cz5RM4", title: "Wow 16", cat: "wow" },
  { id: "86IxNIfMa5zOw", title: "Sad 5", cat: "sad" },
  { id: "8wfma7DJXm46KFsZjK", title: "Happy 15", cat: "happy" },
  { id: "10FHR5A4cXqVrO", title: "Wow 17", cat: "wow" },
  { id: "f9p9GclvDGqcM", title: "Angry 4", cat: "angry" },
  { id: "9r6FZQ5FI8CIYUpLEg", title: "Cute 5", cat: "cute" },
  { id: "ZQMVKzoTLdNBu", title: "Happy 16", cat: "happy" },
  { id: "nbNiYAzTBideb1CpIP", title: "Cute 6", cat: "cute" },
  { id: "PSWCyXQj54nm7d8oZl", title: "Love 5", cat: "love" },
  { id: "KmlTchPoFQT84", title: "Wow 18", cat: "wow" },
  { id: "ozXTrqRgqFcly", title: "Sad 6", cat: "sad" },
  { id: "eatuE5vouR0JfGvSLS", title: "Wow 19", cat: "wow" },
  { id: "lcwrrsfs4Px6w", title: "Happy 17", cat: "happy" },
  { id: "10khKaHKOP2mZ2", title: "Wow 20", cat: "wow" },
  { id: "6qvoDc62nHggNsa0WB", title: "Lol 14", cat: "lol" },
  { id: "3o7TKB3oifq46DDhOE", title: "Happy 18", cat: "happy" },
  { id: "LmZFMTJYBWRzx7z43M", title: "Love 6", cat: "love" },
  { id: "cW6dKzfsEuiL6", title: "Happy 19", cat: "happy" },
  { id: "H1zM6t7Zqi1hK", title: "Love 7", cat: "love" },
  { id: "8bp98Q4HUQuNG", title: "Happy 20", cat: "happy" },
  { id: "XfT1Xb2O2ShHy", title: "Sad 7", cat: "sad" },
  { id: "WZuGWpHtzHBoA", title: "Love 8", cat: "love" },
  { id: "l0ErTYG23Hyn67Fxm", title: "Wow 21", cat: "wow" },
  { id: "26FxypSnWsXS69nTW", title: "Sad 8", cat: "sad" },
  { id: "htqV3EcTHv7JC", title: "Happy 21", cat: "happy" },
  { id: "TfRDVuQr4QYJlmNjfZ", title: "Sad 9", cat: "sad" },
  { id: "GrsGN4NyUkOuk", title: "Wow 22", cat: "wow" },
  { id: "kdWcmOyOmHvvnqYfjT", title: "Lol 15", cat: "lol" },
  { id: "rc4ei6kvLeFyqSuL74", title: "Wow 23", cat: "wow" },
  { id: "ifAgSzpSf3fgAjcIJM", title: "Love 9", cat: "love" },
  { id: "f41oBFWHe3uro7Inqr", title: "Lol 16", cat: "lol" },
  { id: "5pfyDZRvycJQk", title: "Wow 24", cat: "wow" },
  { id: "darauqjZo6FsA", title: "Cute 7", cat: "cute" },
  { id: "YfFbDWIBXppNoMAKlW", title: "Wow 25", cat: "wow" },
  { id: "3o6Zt3KFoI4XUfWmZ2", title: "Happy 22", cat: "happy" },
  { id: "l2JIdnF6aJnAqzDgY", title: "Happy 23", cat: "happy" },
  { id: "L3Y45TZEmhSmY", title: "Angry 5", cat: "angry" },
  { id: "wdbBigwoXMEDSffwHA", title: "Angry 6", cat: "angry" },
  { id: "G8rcbSPfCgs3VDrWi5", title: "Lol 17", cat: "lol" },
  { id: "FIZ1QC610AAhi", title: "Cute 8", cat: "cute" },
  { id: "9KQ86aWlLIpG", title: "Happy 24", cat: "happy" },
  { id: "xTiTnf9SCIVk8HIvE4", title: "Lol 18", cat: "lol" },
  { id: "ShueCGbEVo8ny9uMBT", title: "Happy 25", cat: "happy" },
  { id: "WoF3yfYupTt8mHc7va", title: "Lol 19", cat: "lol" },
  { id: "8UYMQ5MCmuqXu", title: "Cute 9", cat: "cute" },
  { id: "2vpci8MLYEXahWAFRt", title: "Love 10", cat: "love" },
  { id: "KtaWTnLH5P00qoapJe", title: "Lol 20", cat: "lol" },
  { id: "9tT0s3SBnDm4o", title: "Wow 26", cat: "wow" },
  { id: "k4fo3p7p1UlSE", title: "Wow 27", cat: "wow" },
  { id: "3oz8xUK8V7suY7W9SE", title: "Lol 21", cat: "lol" },
  { id: "26qGaINqDqiAdFUjM7", title: "Love 11", cat: "love" },
  { id: "Z3NVDAamiuT4Y", title: "Cute 10", cat: "cute" },
  { id: "WJjLyXCVvro2I", title: "Cute 11", cat: "cute" },
  { id: "BGYhuwxrb4Bck", title: "Lol 22", cat: "lol" },
  { id: "amrNGnZUeWhZC", title: "Wow 28", cat: "wow" },
  { id: "mguPrVJAnEHIY", title: "Wow 29", cat: "wow" },
  { id: "yfx58k3ssqCly", title: "Sad 10", cat: "sad" },
  { id: "6u9t67tyN1mV6VMrf7", title: "Sad 11", cat: "sad" },
  { id: "l3vR8IAtvPQuDgOHu", title: "Happy 26", cat: "happy" },
  { id: "35NGT2lm6mfHlNAkMu", title: "Wow 30", cat: "wow" },
  { id: "xUA7b9kNfcKICBrlks", title: "Sad 12", cat: "sad" },
  { id: "oVaigqUhPvDglQ0uWJ", title: "Wow 31", cat: "wow" },
  { id: "l2JJyDYEX1tXFmCd2", title: "Happy 27", cat: "happy" },
  { id: "7ukAmtG7h6OwZRNJiM", title: "Happy 28", cat: "happy" },
  { id: "l46Cgctdy5C23iB0c", title: "Lol 23", cat: "lol" },
  { id: "Dnt2VnWFknFNm", title: "Angry 7", cat: "angry" },
  { id: "3oKIP8kNuTJJL3zT0I", title: "Lol 24", cat: "lol" },
  { id: "4Ev0Ari2Nd9io", title: "Love 12", cat: "love" },
  { id: "3oKIPs6VsHLpVXnZTy", title: "Wow 32", cat: "wow" },
  { id: "uYe2emzPgDfj2", title: "Happy 29", cat: "happy" },
  { id: "bqm6WOjuLu480", title: "Cute 12", cat: "cute" },
  { id: "l4Ep3mmmj7Bw3adWw", title: "Love 13", cat: "love" },
  { id: "l0MYP6WAFfaR7Q1jO", title: "Lol 25", cat: "lol" },
  { id: "LE9LqDSiIIFdm", title: "Lol 26", cat: "lol" },
  { id: "vXyIMuWbGTMtO", title: "Cute 13", cat: "cute" },
  { id: "26FPr0GKKPaPiUbbG", title: "Lol 27", cat: "lol" },
  { id: "fallYu2VWPHZC", title: "Wow 33", cat: "wow" },
  { id: "4ilFRqgbzbx4c", title: "Wow 34", cat: "wow" },
  { id: "xT8qB72Dfmxd8nv9DO", title: "Lol 28", cat: "lol" },
  { id: "MrxXXBriEIKBO", title: "Wow 35", cat: "wow" },
  { id: "L8A2CLpJJW5d3NR5Tt", title: "Love 14", cat: "love" },
  { id: "rpf0Du8NasK6Q", title: "Happy 30", cat: "happy" },
  { id: "qMIhdDeN93da8", title: "Happy 31", cat: "happy" },
  { id: "UZ41SqwgD7AtO", title: "Cute 14", cat: "cute" },
  { id: "4v2pTGw7t5yUw", title: "Lol 29", cat: "lol" },
  { id: "UxTZDNv0Zej4s", title: "Cute 15", cat: "cute" },
  { id: "X8YmZeoAmqRFK", title: "Wow 36", cat: "wow" },
  { id: "3oKIPiqfUtLCnIKxRS", title: "Angry 8", cat: "angry" },
  { id: "3ohhwmd5YuNXOBg8NO", title: "Happy 32", cat: "happy" },
  { id: "l0Iy6RfxFjVqP8NQQ", title: "Lol 30", cat: "lol" },
  { id: "FHRBnQFkpAeYg", title: "Love 15", cat: "love" },
  { id: "atQF1zaSGq8s8", title: "Angry 9", cat: "angry" },
  { id: "11rIergnpiYpvW", title: "Love 16", cat: "love" },
  { id: "3o752n5SGRA6Uocg4E", title: "Happy 33", cat: "happy" },
  { id: "MUzcUt3KPm4MQbxqLe", title: "Happy 34", cat: "happy" },
  { id: "7iTz3LdCBJJ1C", title: "Lol 31", cat: "lol" },
  { id: "Ass7N88ITsb3a", title: "Cute 16", cat: "cute" },
  { id: "hiLLD9o1wTB3a", title: "Love 17", cat: "love" },
  { id: "3o6vXQ1IrmD6Gezb5m", title: "Lol 32", cat: "lol" },
  { id: "YgmczzYWY4DTO", title: "Happy 35", cat: "happy" },
  { id: "HyOOyynWxMxig", title: "Cute 17", cat: "cute" },
  { id: "26BRsI63ak8uxsU6Y", title: "Wow 37", cat: "wow" },
  { id: "nn2kmb1lRtpkY", title: "Lol 33", cat: "lol" },
  { id: "3eRon7lRelaBCfCU45", title: "Happy 36", cat: "happy" },
  { id: "sBGw5MruxAyiI", title: "Lol 34", cat: "lol" },
  { id: "qiiimDJtLj4XK", title: "Happy 37", cat: "happy" },
  { id: "SRNALfyywIzuKhHOln", title: "Happy 38", cat: "happy" },
  { id: "l9JTCGoQddYBO", title: "Sad 13", cat: "sad" },
  { id: "okWCAjMp0pInC", title: "Wow 38", cat: "wow" },
  { id: "BWJ5HDG6T5lK0", title: "Love 18", cat: "love" },
  { id: "zOCCrwRQgeqCk", title: "Love 19", cat: "love" },
  { id: "8PqTcO444vDj2", title: "Happy 39", cat: "happy" },
  { id: "KAV8WgWgDjpLz9muwI", title: "Wow 39", cat: "wow" },
  { id: "zrIF3F5J3i0pO", title: "Wow 40", cat: "wow" },
  { id: "xT39D16Uj3x2G4H01q", title: "Lol 35", cat: "lol" },
  { id: "3ohhwHHhB9qckB1Af6", title: "Lol 36", cat: "lol" },
  { id: "h5vOKbZbkDO93yUO4f", title: "Lol 37", cat: "lol" },
  { id: "bYR0iptD1PaqQ", title: "Wow 41", cat: "wow" },
  { id: "ispEc1253326c", title: "Wow 42", cat: "wow" },
  { id: "nrXif9YExO9EI", title: "Wow 43", cat: "wow" },
  { id: "QIQyvt68Tez1S", title: "Love 20", cat: "love" },
  { id: "euZGuGUM7UBA4", title: "Love 21", cat: "love" },
  { id: "Y4nRHo9guQrPWuW5Zv", title: "Lol 38", cat: "lol" },
  { id: "OpYV9CBVZOb1S", title: "Cute 18", cat: "cute" },
  { id: "nne49HiWVG87XbPYFr", title: "Wow 44", cat: "wow" },
  { id: "J8iyDI9bZb6ve", title: "Angry 10", cat: "angry" },
  { id: "u1SH63gOjMPpS", title: "Sad 14", cat: "sad" },
  { id: "kBYniXGn9rSn75AS3l", title: "Happy 40", cat: "happy" },
  { id: "l2JdW3jH05UwUCagE", title: "Sad 15", cat: "sad" },
  { id: "KJLsTTsF5ruMg", title: "Sad 16", cat: "sad" },
  { id: "a0KBCGQDHKidO", title: "Wow 45", cat: "wow" },
  { id: "3og0ISzBpn0nNJE3Ac", title: "Cute 19", cat: "cute" },
  { id: "SrDsJj5i1Chm8", title: "Lol 39", cat: "lol" },
  { id: "qriH9W51oLsL6", title: "Happy 41", cat: "happy" },
  { id: "Hld1RfHBeQDmM", title: "Cute 20", cat: "cute" },
  { id: "7d7lKk2nH5RJu", title: "Angry 11", cat: "angry" },
  { id: "fWgwAXmG6dhR2MXaG8", title: "Cute 21", cat: "cute" },
  { id: "l0HlPtbGpcnqa0fja", title: "Happy 42", cat: "happy" },
  { id: "9cpDS5h2E7p9f98pLd", title: "Wow 46", cat: "wow" },
  { id: "tqiYB9X6goN68", title: "Lol 40", cat: "lol" },
  { id: "NxGQZ6BYEp98y6LWht", title: "Amabatu 1", cat: "amabatu" },
  { id: "Rg5RFYLefosZ4vRqmn", title: "Amabatu 2", cat: "amabatu" },
  { id: "SNpn8mDGHZFpBVxIIp", title: "Amabatu 3", cat: "amabatu" },
  { id: "83NJRgoBI1O3sjpiMO", title: "Amabatu 4", cat: "amabatu" },
  { id: "LvBxvy0ENzZ3h8FwEy", title: "Amabatu 5", cat: "amabatu" },
  { id: "lNI0jQ9g70dnGyKPCN", title: "Amabatu 6", cat: "amabatu" },
  { id: "Dbbxgf4N6fMfoSXy3C", title: "Amabatu 7", cat: "amabatu" },
  { id: "oVsCrm7SP5xprtZy4r", title: "Amabatu 8", cat: "amabatu" },
  { id: "6a1rpnAsT1uIg8VtUZ", title: "Amabatu 9", cat: "amabatu" },
  { id: "9oryRGyTdzzFEBUgcb", title: "Amabatu 10", cat: "amabatu" },
  { id: "4Ri3wZqFjICSMS75J0", title: "Amabatu 11", cat: "amabatu" },
  { id: "srRkdciWIOsppQhPBW", title: "Amabatu 12", cat: "amabatu" },
  { id: "iH9SL9LHTuDyyOvd90", title: "Amabatu 13", cat: "amabatu" },
  { id: "36M4MGJNRIMOdMLtVt", title: "Amabatu 14", cat: "amabatu" },
  { id: "gNjSEUHYeGVAiSRwyt", title: "Amabatu 15", cat: "amabatu" },
  { id: "3HoeeTJjQ5IDQYXdap", title: "Amabatu 16", cat: "amabatu" },
  { id: "L0nhTaYf038ZqDMZpY", title: "Amabatu 17", cat: "amabatu" },
  { id: "o5ht0KxTJDAS90MNWI", title: "Dreamy Bull", cat: "amabatu" },
  { id: "ttT5xsI6990yrYlumF", title: "Amabatu 19", cat: "amabatu" },
  { id: "Gzinj1YEi8lxMt2Ddi", title: "Amabatu 20", cat: "amabatu" },
  { id: "s4b6syHmVTioGJw2ZG", title: "Amabatu 21", cat: "amabatu" },
  { id: "wO0PCfoBY5XjHsGzA6", title: "Amabatu 22", cat: "amabatu" },
  { id: "UcgV0KLpwgvVmHKkxJ", title: "Amabatu 23", cat: "amabatu" },
  { id: "ZD6HHQn2d9TdGktJ0y", title: "Amabatu 24", cat: "amabatu" },
  { id: "uzCED5gEt7ikYWg0ne", title: "Amabatu 25", cat: "amabatu" },
  { id: "j9q4yFMcXY2n6nURNL", title: "Amabatu 26", cat: "amabatu" },
  { id: "pPFhziKTBD8SJgP3Ko", title: "Amabatu 27", cat: "amabatu" },
  { id: "F46ILAlX50PBssjtdl", title: "Amabatu 28", cat: "amabatu" },
  { id: "bTnjjJn4pJLFUa0CLP", title: "Amabatu 29", cat: "amabatu" },
  { id: "1MVzbtKKLn9lCERT7v", title: "Amabatu 30", cat: "amabatu" },
  { id: "x5iaeyvCnc8oxTw9os", title: "Amabatu 31", cat: "amabatu" },
]

function gifUrl(id) { return `https://media.giphy.com/media/${id}/giphy.gif` }
function previewUrl(id) { return `https://media.giphy.com/media/${id}/100w.gif` }

export default function GifPicker({ onSelect, onClose, simple }) {
  const [cat, setCat] = useState("All")

  const cats = [
    { name: "All", fn: () => true },
    { name: "Happy", fn: g => g.cat === "happy" },
    { name: "LOL", fn: g => g.cat === "lol" },
    { name: "Wow", fn: g => g.cat === "wow" },
    { name: "Sad", fn: g => g.cat === "sad" },
    { name: "Cute", fn: g => g.cat === "cute" },
    { name: "Angry", fn: g => g.cat === "angry" },
    { name: "Love", fn: g => g.cat === "love" },
    { name: "Amabatu", fn: g => g.cat === "amabatu" },
  ]

  const filtered = cat === "All" ? GIFS : GIFS.filter(cats.find(c => c.name === cat).fn)

  const content = (
    <>
      <div style={{
        display: "flex", gap: "0.25rem", padding: "0.4rem 0.5rem",
        borderBottom: "1px solid #333", overflowX: "auto", flexShrink: 0,
      }}>
        {cats.map(c => (
          <button key={c.name} onClick={() => setCat(c.name)} style={{
            padding: "0.25rem 0.6rem", borderRadius: "12px", border: "none",
            background: cat === c.name ? "#2563eb" : "#2a2a2a",
            color: cat === c.name ? "#fff" : "#ccc",
            cursor: "pointer", fontSize: "0.75rem", whiteSpace: "nowrap",
            flexShrink: 0,
          }}>{c.name} {c.name === "All" ? `(${GIFS.length})` : `(${GIFS.filter(cats.find(x => x.name === c.name).fn).length})`}</button>
        ))}
        {!simple && (
          <button onClick={onClose} style={{
            marginLeft: "auto", background: "none", border: "none",
            color: "#999", cursor: "pointer", fontSize: "1rem", padding: "0 0.2rem",
          }}>&#10005;</button>
        )}
      </div>
      <div style={{
        display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(80px, 1fr))", gap: "3px",
        padding: "4px", overflowY: "auto", contentVisibility: "auto",
        ...(simple ? { flex: 1 } : { maxHeight: "300px" }),
      }}>
        {filtered.map(g => (
          <div key={g.id} style={{ width: "100%", aspectRatio: "1", borderRadius: "4px", background: "#0f0f0f" }}>
            <img src={previewUrl(g.id)} alt=""
              onClick={() => onSelect(gifUrl(g.id))}
              title={g.title}
              referrerPolicy="no-referrer"
              onError={(e) => { e.target.style.opacity = "0" }}
              style={{
                width: "100%", height: "100%", objectFit: "cover", borderRadius: "4px",
                cursor: "pointer", display: "block",
              }}
              loading="lazy"
            />
          </div>
        ))}
      </div>
    </>
  )

  if (simple) {
    return content
  }

  return (
    <div style={{
      position: "absolute", bottom: "100%", left: 0, right: 0,
      width: "100%", maxWidth: "400px", margin: "0 auto",
      background: "#1a1a1a", border: "1px solid #333", borderRadius: "10px 10px 0 0",
      overflow: "hidden", zIndex: 200, display: "flex", flexDirection: "column",
    }}>
      {content}
    </div>
  )
}
